
import type { Product, Order } from './types';

export const products: Product[] = [
  {
    id: "FMCG001",
    name: "Parle-G Original Biscuits (250g)",
    category: "FMCG",
    stock: 2500,
    capacity: 3000,
    threshold: 500,
    price: 25,
    imageUrl: "https://i.ibb.co/L9t0bJ8/parle-g-original-biscuits-250g.png",
    historicalSalesData: Array.from({ length: 30 }, (_, i) => ({ date: `2023-05-${String(i + 1).padStart(2, '0')}`, quantity: 150 + Math.floor(Math.random() * 50) })),
  },
  {
    id: "FMCG002",
    name: "Britannia Good Day Butter Cookies (200g)",
    category: "FMCG",
    stock: 1800,
    capacity: 2000,
    threshold: 350,
    price: 50,
    imageUrl: "https://i.ibb.co/mHvqM8J/britannia-good-day-butter-cookies-200g.png",
    historicalSalesData: Array.from({ length: 30 }, (_, i) => ({ date: `2023-05-${String(i + 1).padStart(2, '0')}`, quantity: 80 + Math.floor(Math.random() * 20) })),
  },
  {
    id: "FMCG003",
    name: "Haldiram's Aloo Bhujia (150g)",
    category: "FMCG",
    stock: 1200,
    capacity: 1500,
    threshold: 250,
    price: 40,
    imageUrl: "https://i.ibb.co/GcJ33T3/haldiram-s-aloo-bhujia-150g.png",
    historicalSalesData: Array.from({ length: 30 }, (_, i) => ({ date: `2023-05-${String(i + 1).padStart(2, '0')}`, quantity: 60 + Math.floor(Math.random() * 15) })),
  },
  {
    id: "FMCG004",
    name: "Lay's Classic Salted Potato Chips (52g)",
    category: "FMCG",
    stock: 3000,
    capacity: 4000,
    threshold: 600,
    price: 20,
    imageUrl: "https://i.ibb.co/qj5b65L/lay-s-classic-salted-potato-chips-52g.png",
    historicalSalesData: Array.from({ length: 30 }, (_, i) => ({ date: `2023-05-${String(i + 1).padStart(2, '0')}`, quantity: 200 + Math.floor(Math.random() * 70) })),
  },
  {
    id: "FMCG005",
    name: "Coca-Cola Soft Drink (600ml)",
    category: "FMCG",
    stock: 1500,
    capacity: 2000,
    threshold: 300,
    price: 40,
    imageUrl: "https://i.ibb.co/VMywDWs/coca-cola-soft-drink-600ml.png",
    historicalSalesData: Array.from({ length: 30 }, (_, i) => ({ date: `2023-05-${String(i + 1).padStart(2, '0')}`, quantity: 100 + Math.floor(Math.random() * 30) })),
  },
  {
    id: "FMCG006",
    name: "Frooti Mango Drink (1L)",
    category: "FMCG",
    stock: 700,
    capacity: 1000,
    threshold: 150,
    price: 100,
    imageUrl: "https://i.ibb.co/Xz9J2dm/frooti-mango-drink-1l.png",
    historicalSalesData: Array.from({ length: 30 }, (_, i) => ({ date: `2023-05-${String(i + 1).padStart(2, '0')}`, quantity: 50 + Math.floor(Math.random() * 20) })),
  },
  {
    id: "FMCG007",
    name: "Tata Tea Gold (500g)",
    category: "FMCG",
    stock: 900,
    capacity: 1000,
    threshold: 180,
    price: 280,
    imageUrl: "https://i.ibb.co/D9pnp1N/tata-tea-gold-500g.png",
    historicalSalesData: Array.from({ length: 30 }, (_, i) => ({ date: `2023-05-${String(i + 1).padStart(2, '0')}`, quantity: 40 + Math.floor(Math.random() * 10) })),
  },
  {
    id: "FMCG008",
    name: "Nescafe Classic Instant Coffee (100g)",
    category: "FMCG",
    stock: 600,
    capacity: 700,
    threshold: 120,
    price: 160,
    imageUrl: "https://i.ibb.co/RSCyG9R/nescafe-classic-instant-coffee-100g.png",
    historicalSalesData: Array.from({ length: 30 }, (_, i) => ({ date: `2023-05-${String(i + 1).padStart(2, '0')}`, quantity: 30 + Math.floor(Math.random() * 10) })),
  },
  {
    id: "FMCG009",
    name: "Maggi 2-Minute Noodles Masala (70g)",
    category: "FMCG",
    stock: 4000,
    capacity: 5000,
    threshold: 800,
    price: 15,
    imageUrl: "https://i.ibb.co/XSCxS2g/maggi-2-minute-noodles-masala-70g.png",
    historicalSalesData: Array.from({ length: 30 }, (_, i) => ({ date: `2023-05-${String(i + 1).padStart(2, '0')}`, quantity: 250 + Math.floor(Math.random() * 80) })),
  },
  {
    id: "FMCG010",
    name: "Amul Butter (500g)",
    category: "Dairy",
    stock: 1100,
    capacity: 1200,
    threshold: 220,
    price: 250,
    imageUrl: "https://i.ibb.co/Hhzj1K5/amul-butter-500g.png",
    historicalSalesData: Array.from({ length: 30 }, (_, i) => ({ date: `2023-05-${String(i + 1).padStart(2, '0')}`, quantity: 60 + Math.floor(Math.random() * 20) })),
  },
  {
    id: "FMCG011",
    name: "Aashirvaad Atta (5kg)",
    category: "Grocery",
    stock: 800,
    capacity: 1000,
    threshold: 160,
    price: 280,
    imageUrl: "https://i.ibb.co/VJxB8z1/aashirvaad-atta-5kg.png",
    historicalSalesData: Array.from({ length: 30 }, (_, i) => ({ date: `2023-05-${String(i + 1).padStart(2, '0')}`, quantity: 50 + Math.floor(Math.random() * 15) })),
  },
  {
    id: "FMCG012",
    name: "Daawat Basmati Rice (1kg)",
    category: "Grocery",
    stock: 750,
    capacity: 800,
    threshold: 150,
    price: 120,
    imageUrl: "https://i.ibb.co/dDThc0H/daawat-basmati-rice-1kg.png",
    historicalSalesData: Array.from({ length: 30 }, (_, i) => ({ date: `2023-05-${String(i + 1).padStart(2, '0')}`, quantity: 45 + Math.floor(Math.random() * 10) })),
  },
  {
    id: "FMCG013",
    name: "Tata Sampann Toor Dal (1kg)",
    category: "Grocery",
    stock: 600,
    capacity: 700,
    threshold: 120,
    price: 140,
    imageUrl: "https://i.ibb.co/mSChf84/tata-sampann-toor-dal-1kg.png",
    historicalSalesData: Array.from({ length: 30 }, (_, i) => ({ date: `2023-05-${String(i + 1).padStart(2, '0')}`, quantity: 40 + Math.floor(Math.random() * 10) })),
  },
  {
    id: "FMCG014",
    name: "Fortune Refined Sunflower Oil (1L)",
    category: "Grocery",
    stock: 550,
    capacity: 600,
    threshold: 110,
    price: 160,
    imageUrl: "https://i.ibb.co/8Y0zJ8Q/fortune-refined-sunflower-oil-1l.png",
    historicalSalesData: Array.from({ length: 30 }, (_, i) => ({ date: `2023-05-${String(i + 1).padStart(2, '0')}`, quantity: 35 + Math.floor(Math.random() * 10) })),
  },
  {
    id: "FMCG015",
    name: "Sugar (1kg)",
    category: "Grocery",
    stock: 1000,
    capacity: 1200,
    threshold: 200,
    price: 45,
    imageUrl: "https://i.ibb.co/fDYs4z3/sugar-1kg.png",
    historicalSalesData: Array.from({ length: 30 }, (_, i) => ({ date: `2023-05-${String(i + 1).padStart(2, '0')}`, quantity: 70 + Math.floor(Math.random() * 20) })),
  },
  {
    id: "FMCG016",
    name: "Salt (1kg)",
    category: "Grocery",
    stock: 1200,
    capacity: 1500,
    threshold: 240,
    price: 20,
    imageUrl: "https://i.ibb.co/SnsyT7M/salt-1kg.png",
    historicalSalesData: Array.from({ length: 30 }, (_, i) => ({ date: `2023-05-${String(i + 1).padStart(2, '0')}`, quantity: 80 + Math.floor(Math.random() * 20) })),
  },
  {
    id: "FMCG017",
    name: "Cadbury Dairy Milk Chocolate (50g)",
    category: "FMCG",
    stock: 2000,
    capacity: 2500,
    threshold: 400,
    price: 60,
    imageUrl: "https://i.ibb.co/0FDhBq1/cadbury-dairy-milk-chocolate-50g.png",
    historicalSalesData: Array.from({ length: 30 }, (_, i) => ({ date: `2023-05-${String(i + 1).padStart(2, '0')}`, quantity: 120 + Math.floor(Math.random() * 40) })),
  },
  {
    id: "FMCG018",
    name: "Kwality Walls Vanilla Ice Cream (700ml)",
    category: "Dairy",
    stock: 300,
    capacity: 400,
    threshold: 60,
    price: 180,
    imageUrl: "https://i.ibb.co/r2gPzct/kwality-walls-vanilla-ice-cream-700ml.png",
    historicalSalesData: Array.from({ length: 30 }, (_, i) => ({ date: `2023-05-${String(i + 1).padStart(2, '0')}`, quantity: 20 + Math.floor(Math.random() * 10) })),
  },
  {
    id: "FMCG019",
    name: "Knorr Sweet Corn Veg Soup (43g)",
    category: "FMCG",
    stock: 400,
    capacity: 500,
    threshold: 80,
    price: 50,
    imageUrl: "https://i.ibb.co/y4YJq2L/knorr-sweet-corn-veg-soup-43g.png",
    historicalSalesData: Array.from({ length: 30 }, (_, i) => ({ date: `2023-05-${String(i + 1).padStart(2, '0')}`, quantity: 25 + Math.floor(Math.random() * 10) })),
  },
  {
    id: "FMCG020",
    name: "Sunfeast Yippee! Magic Masala Noodles (70g)",
    category: "FMCG",
    stock: 1800,
    capacity: 2000,
    threshold: 360,
    price: 15,
    imageUrl: "https://i.ibb.co/gR2YyCg/sunfeast-yippee-magic-masala-noodles-70g.png",
    historicalSalesData: Array.from({ length: 30 }, (_, i) => ({ date: `2023-05-${String(i + 1).padStart(2, '0')}`, quantity: 100 + Math.floor(Math.random() * 30) })),
  },
  {
    id: "FMCG021",
    name: "Mother Dairy Curd (400g)",
    category: "Dairy",
    stock: 600,
    capacity: 700,
    threshold: 120,
    price: 35,
    imageUrl: "https://i.ibb.co/yQjKMSL/mother-dairy-curd-400g.png",
    historicalSalesData: Array.from({ length: 30 }, (_, i) => ({ date: `2023-05-${String(i + 1).padStart(2, '0')}`, quantity: 40 + Math.floor(Math.random() * 15) })),
  },
  {
    id: "FMCG022",
    name: "Britannia Whole Wheat Bread (400g)",
    category: "FMCG",
    stock: 400,
    capacity: 500,
    threshold: 80,
    price: 40,
    imageUrl: "https://i.ibb.co/bX1sC4f/britannia-whole-wheat-bread-400g.png",
    historicalSalesData: Array.from({ length: 30 }, (_, i) => ({ date: `2023-05-${String(i + 1).padStart(2, '0')}`, quantity: 30 + Math.floor(Math.random() * 10) })),
  },
  {
    id: "FMCG023",
    name: "Dabur Honey (250g)",
    category: "FMCG",
    stock: 300,
    capacity: 400,
    threshold: 60,
    price: 120,
    imageUrl: "https://i.ibb.co/2vWfTj8/dabur-honey-250g.png",
    historicalSalesData: Array.from({ length: 30 }, (_, i) => ({ date: `2023-05-${String(i + 1).padStart(2, '0')}`, quantity: 20 + Math.floor(Math.random() * 5) })),
  },
  {
    id: "FMCG024",
    name: "Kissan Mixed Fruit Jam (500g)",
    category: "FMCG",
    stock: 250,
    capacity: 300,
    threshold: 50,
    price: 150,
    imageUrl: "https://i.ibb.co/zXjJtJ6/kissan-mixed-fruit-jam-500g.png",
    historicalSalesData: Array.from({ length: 30 }, (_, i) => ({ date: `2023-05-${String(i + 1).padStart(2, '0')}`, quantity: 15 + Math.floor(Math.random() * 5) })),
  },
  {
    id: "FMCG025",
    name: "Catch Sprinklers Black Pepper (50g)",
    category: "Grocery",
    stock: 350,
    capacity: 400,
    threshold: 70,
    price: 70,
    imageUrl: "https://i.ibb.co/nMSdwb8/catch-sprinklers-black-pepper-50g.png",
    historicalSalesData: Array.from({ length: 30 }, (_, i) => ({ date: `2023-05-${String(i + 1).padStart(2, '0')}`, quantity: 20 + Math.floor(Math.random() * 5) })),
  },
  {
    id: "ELEC001",
    name: "Redmi Note 13 Pro (8GB RAM, 128GB Storage)",
    category: "Electronics",
    stock: 80,
    capacity: 100,
    threshold: 15,
    price: 18999,
    imageUrl: "https://i.ibb.co/zZ38YxT/redmi-note-13-pro-8gb-ram-128gb-storage.png",
    historicalSalesData: Array.from({ length: 30 }, (_, i) => ({ date: `2023-05-${String(i + 1).padStart(2, '0')}`, quantity: 5 + Math.floor(Math.random() * 3) })),
  },
  {
    id: "ELEC002",
    name: "Samsung Galaxy A55 (6GB RAM, 128GB Storage)",
    category: "Electronics",
    stock: 70,
    capacity: 80,
    threshold: 12,
    price: 25999,
    imageUrl: "https://i.ibb.co/yQjKMSL/samsung-galaxy-a55-6gb-ram-128gb-storage.png",
    historicalSalesData: Array.from({ length: 30 }, (_, i) => ({ date: `2023-05-${String(i + 1).padStart(2, '0')}`, quantity: 4 + Math.floor(Math.random() * 3) })),
  },
  {
    id: "ELEC003",
    name: "Apple iPhone 15 (128GB)",
    category: "Electronics",
    stock: 40,
    capacity: 50,
    threshold: 8,
    price: 79900,
    imageUrl: "https://i.ibb.co/1mZz3rv/apple-iphone-15-128gb.png",
    historicalSalesData: Array.from({ length: 30 }, (_, i) => ({ date: `2023-05-${String(i + 1).padStart(2, '0')}`, quantity: 2 + Math.floor(Math.random() * 2) })),
  },
  {
    id: "PC001",
    name: "Dettol Original Soap (125g, Pack of 4)",
    category: "Personal Care",
    stock: 700,
    capacity: 800,
    threshold: 140,
    price: 180,
    imageUrl: "https://i.ibb.co/tZ2x8rV/dettol-original-soap-125g-pack-of-4.png",
    historicalSalesData: Array.from({ length: 30 }, (_, i) => ({ date: `2023-05-${String(i + 1).padStart(2, '0')}`, quantity: 40 + Math.floor(Math.random() * 10) })),
  },
  {
    id: "PC004",
    name: "Himalaya Herbals Purifying Neem Face Wash (150ml)",
    category: "Personal Care",
    stock: 400,
    capacity: 500,
    threshold: 80,
    price: 140,
    imageUrl: "https://i.ibb.co/5cWJc9g/himalaya-herbals-purifying-neem-face-wash-150ml.png",
    historicalSalesData: Array.from({ length: 30 }, (_, i) => ({ date: `2023-05-${String(i + 1).padStart(2, '0')}`, quantity: 25 + Math.floor(Math.random() * 8) })),
  },
  {
    id: "HH001",
    name: "Lizol Disinfectant Floor Cleaner (1L)",
    category: "Household",
    stock: 600,
    capacity: 700,
    threshold: 120,
    price: 180,
    imageUrl: "https://i.ibb.co/sKkY9jD/lizol-disinfectant-floor-cleaner-1l.png",
    historicalSalesData: Array.from({ length: 30 }, (_, i) => ({ date: `2023-05-${String(i + 1).padStart(2, '0')}`, quantity: 35 + Math.floor(Math.random() * 10) })),
  },
  {
    id: "HH002",
    name: "Harpic Powerplus Toilet Cleaner (750ml)",
    category: "Household",
    stock: 550,
    capacity: 600,
    threshold: 110,
    price: 120,
    imageUrl: "https://i.ibb.co/7nB3rGp/harpic-powerplus-toilet-cleaner-750ml.png",
    historicalSalesData: Array.from({ length: 30 }, (_, i) => ({ date: `2023-05-${String(i + 1).padStart(2, '0')}`, quantity: 30 + Math.floor(Math.random() * 10) })),
  }
];


export const orders: Order[] = [
  { id: 'ORD-001', customerName: 'Rohan Sharma', customerId: 'FS-458921', items: [{ productName: 'Britannia Good Day Butter Cookies (200g)', quantity: 2 }, { productName: 'Tata Tea Gold (500g)', quantity: 1 }], status: 'Shipped', date: '2023-06-15' },
  { id: 'ORD-002', customerName: 'Priya Verma', customerId: 'FS-102384', items: [{ productName: 'Redmi Note 13 Pro (8GB RAM, 128GB Storage)', quantity: 1 }], status: 'Delivered', date: '2023-06-14' },
  { id: 'ORD-003', customerName: 'Anjali Mehta', customerId: 'FS-983471', items: [{ productName: 'Dettol Original Soap (125g, Pack of 4)', quantity: 1 }, { productName: 'Lizol Disinfectant Floor Cleaner (1L)', quantity: 1 }], status: 'Packed', date: '2023-06-16' },
  { id: 'ORD-004', customerName: 'Vikram Singh', customerId: 'FS-234567', items: [{ productName: 'Aashirvaad Atta (5kg)', quantity: 2 }], status: 'Processing', date: '2023-06-16' },
  { id: 'ORD-005', customerName: 'Sunita Reddy', customerId: 'FS-876543', items: [{ productName: 'Lay\'s Classic Salted Potato Chips (52g)', quantity: 10 }], status: 'Shipped', date: '2023-06-15' },
];

export const salesData = [
  { name: 'Jan', sales: 450000 },
  { name: 'Feb', sales: 480000 },
  { name: 'Mar', sales: 520000 },
  { name: 'Apr', sales: 490000 },
  { name: 'May', sales: 550000 },
  { name: 'Jun', sales: 580000 },
];
