
import type { Product, Order } from './types';

export const products: Product[] = [
  {
    id: 'prod_001',
    name: 'Classic Soap',
    category: 'FMCG',
    stock: 150,
    capacity: 500,
    threshold: 50,
    price: 40,
    imageUrl: 'https://picsum.photos/200/200?random=1',
    historicalSalesData: Array.from({ length: 30 }, (_, i) => ({ date: `2023-05-${String(i + 1).padStart(2, '0')}`, quantity: 10 + Math.floor(Math.random() * 15) })),
  },
  {
    id: 'prod_002',
    name: 'Herbal Shampoo',
    category: 'FMCG',
    stock: 80,
    capacity: 300,
    threshold: 40,
    price: 150,
    imageUrl: 'https://picsum.photos/200/200?random=2',
    historicalSalesData: Array.from({ length: 30 }, (_, i) => ({ date: `2023-05-${String(i + 1).padStart(2, '0')}`, quantity: 5 + Math.floor(Math.random() * 10) })),
  },
   {
    id: 'prod_009',
    name: 'Coconut Oil',
    category: 'FMCG',
    stock: 120,
    capacity: 400,
    threshold: 50,
    price: 90,
    imageUrl: 'https://picsum.photos/200/200?random=9',
    historicalSalesData: Array.from({ length: 30 }, (_, i) => ({ date: `2023-05-${String(i + 1).padStart(2, '0')}`, quantity: 12 + Math.floor(Math.random() * 10) })),
  },
  {
    id: 'prod_003',
    name: 'Painkiller Tablets',
    category: 'Pharmaceuticals',
    stock: 25,
    capacity: 200,
    threshold: 30,
    price: 99,
    imageUrl: 'https://picsum.photos/200/200?random=3',
    historicalSalesData: Array.from({ length: 30 }, (_, i) => ({ date: `2023-05-${String(i + 1).padStart(2, '0')}`, quantity: 2 + Math.floor(Math.random() * 5) })),
  },
  {
    id: 'prod_010',
    name: 'Antacid Syrup',
    category: 'Pharmaceuticals',
    stock: 50,
    capacity: 150,
    threshold: 20,
    price: 120,
    imageUrl: 'https://picsum.photos/200/200?random=10',
    historicalSalesData: Array.from({ length: 30 }, (_, i) => ({ date: `2023-05-${String(i + 1).padStart(2, '0')}`, quantity: 4 + Math.floor(Math.random() * 6) })),
  },
  {
    id: 'prod_004',
    name: 'USB-C Charger',
    category: 'Electronics',
    stock: 120,
    capacity: 250,
    threshold: 50,
    price: 599,
    imageUrl: 'https://picsum.photos/200/200?random=4',
    historicalSalesData: Array.from({ length: 30 }, (_, i) => ({ date: `2023-05-${String(i + 1).padStart(2, '0')}`, quantity: 8 + Math.floor(Math.random() * 12) })),
  },
   {
    id: 'prod_011',
    name: 'Power Bank',
    category: 'Electronics',
    stock: 90,
    capacity: 200,
    threshold: 30,
    price: 1299,
    imageUrl: 'https://picsum.photos/200/200?random=11',
    historicalSalesData: Array.from({ length: 30 }, (_, i) => ({ date: `2023-05-${String(i + 1).padStart(2, '0')}`, quantity: 6 + Math.floor(Math.random() * 8) })),
  },
  {
    id: 'prod_005',
    name: 'Basmati Rice (1kg)',
    category: 'Grocery',
    stock: 200,
    capacity: 1000,
    threshold: 100,
    price: 120,
    imageUrl: 'https://picsum.photos/200/200?random=5',
    historicalSalesData: Array.from({ length: 30 }, (_, i) => ({ date: `2023-05-${String(i + 1).padStart(2, '0')}`, quantity: 20 + Math.floor(Math.random() * 25) })),
  },
  {
    id: 'prod_012',
    name: 'Lentils (Toor Dal) (1kg)',
    category: 'Grocery',
    stock: 300,
    capacity: 800,
    threshold: 150,
    price: 150,
    imageUrl: 'https://picsum.photos/200/200?random=12',
    historicalSalesData: Array.from({ length: 30 }, (_, i) => ({ date: `2023-05-${String(i + 1).padStart(2, '0')}`, quantity: 25 + Math.floor(Math.random() * 20) })),
  },
  {
    id: 'prod_006',
    name: 'Packaging Boxes (L)',
    category: 'Warehouse',
    stock: 450,
    capacity: 2000,
    threshold: 200,
    price: 25,
    imageUrl: 'https://picsum.photos/200/200?random=6',
    historicalSalesData: Array.from({ length: 30 }, (_, i) => ({ date: `2023-05-${String(i + 1).padStart(2, '0')}`, quantity: 50 + Math.floor(Math.random() * 40) })),
  },
  {
    id: 'prod_007',
    name: 'Gel Pens (Pack of 5)',
    category: 'Stationery',
    stock: 75,
    capacity: 400,
    threshold: 50,
    price: 50,
    imageUrl: 'https://picsum.photos/200/200?random=7',
    historicalSalesData: Array.from({ length: 30 }, (_, i) => ({ date: `2023-05-${String(i + 1).padStart(2, '0')}`, quantity: 15 + Math.floor(Math.random() * 10) })),
  },
  {
    id: 'prod_008',
    name: 'Potato Chips',
    category: 'FMCG',
    stock: 30,
    capacity: 250,
    threshold: 50,
    price: 20,
    imageUrl: 'https://picsum.photos/200/200?random=8',
    historicalSalesData: Array.from({ length: 30 }, (_, i) => ({ date: `2023-05-${String(i + 1).padStart(2, '0')}`, quantity: 30 + Math.floor(Math.random() * 20) })),
  },
];

export const orders: Order[] = [
  { id: 'ORD-001', customerName: 'John Doe', items: [{ productName: 'Classic Soap', quantity: 5 }, { productName: 'Herbal Shampoo', quantity: 2 }], status: 'Shipped', date: '2023-06-15' },
  { id: 'ORD-002', customerName: 'Jane Smith', items: [{ productName: 'USB-C Charger', quantity: 1 }], status: 'Delivered', date: '2023-06-14' },
  { id: 'ORD-003', customerName: 'Emily Jones', items: [{ productName: 'Painkiller Tablets', quantity: 1 }, { productName: 'Gel Pens (Pack of 5)', quantity: 3 }], status: 'Packed', date: '2023-06-16' },
  { id: 'ORD-004', customerName: 'Michael Brown', items: [{ productName: 'Basmati Rice (1kg)', quantity: 10 }], status: 'Processing', date: '2023-06-16' },
  { id: 'ORD-005', customerName: 'Jessica Williams', items: [{ productName: 'Potato Chips', quantity: 8 }], status: 'Shipped', date: '2023-06-15' },
];

export const salesData = [
  { name: 'Jan', sales: 300000 },
  { name: 'Feb', sales: 250000 },
  { name: 'Mar', sales: 400000 },
  { name: 'Apr', sales: 350000 },
  { name: 'May', sales: 450000 },
  { name: 'Jun', sales: 420000 },
];
